spring:
  config:
    import:
      - classpath:/application-secret.yml
#  config:
#    activate:
#      on-profile: local
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
  mail:
    host: smtp.naver.com
    port: 465
    properties:
      debug: true
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: smtp.naver.com
          starttls:
            enable: true
  redis:
    host: 127.0.0.1
    port: 6379

# p6spy ?? ??
decorator:
  datasource:
    p6spy:
      enable-logging: true